title: Opensource projects
url: http://seznam.github.io
description: >
    We provide our gimmicks for web development in the public space as open source.
safe: false
auto: true
server: false
server_port: 4000
baseurl: /
url: http://localhost:4000

source: .
destination: ./_site
plugins: ./_plugins

future: true
lsi: false
pygments: true
markdown: maruku
permalink: date


# Seznam projektů
projects:
  
  # Testovací projekt
  - key: test      
    title: Seznam Opensource
    url: /test/index.html
    description: >
        Projekt, na kterém se snažíme ukázat práci s Jekyllem, vytvoření nového projektu do služby Opensource Seznam.
    keywords: >
        opensource,showcase,project
    version: 1.2
    download: https://github.com/seznam/seznam.github.io.git
    features:
      - title: Jekyll
        perex: >
            Transformuje plain text na statické webové stránky a blog.
      - title: Pygments highlighter
        perex: >
            Zvýrazňovač syntaxí v Pythonu s podporou 100 jazyků.
      - title: Pre-defined layouts
        perex: >
            Předchystané šablony pro jednotlivé části projektů.
    menu:
      - link:
        title: "About"
        url: "/test/index.html"
      - link:
        title: "Začínáme"
        url: "/test/documentation/index.html"
      - link:
        title: "Vytvoření nového projektu"
        url: "/test/documentation/new-project.html"