title: Opensource projects
url: http://seznam.github.io
description: >
    We provide our gimmicks for web development in the public space as open source.
safe: false
auto: true
server: false
server_port: 4000
baseurl: /
url: http://localhost:4000

source: .
destination: ./_site
plugins: ./_plugins

future: true
lsi: false
pygments: true
markdown: maruku
permalink: date


# Seznam projektů
projects:
  
  # Testovací projekt
  - key: test      
    title: TEST project
    url: /test/index.html
    description: >
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sagittis porta ligula, a consectetur purus malesuada nec.
    keywords: >
        test,new
    version: 1.0 beta
    download: https://github.com/seznam/JAK  
    features:
      - title: Code highlighter
        perex: >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sagittis porta ligula, a consectetur purus malesuada nec.
      - title: CSS pre-defined
        perex: >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sagittis porta ligula, a consectetur purus malesuada nec.
      - title: HTML5 doc structure
        perex: >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sagittis porta ligula, a consectetur purus malesuada nec.            
    menu:
      - link:
        title: "Test project"
        url: "/test/index.html"
      - link:
        title: "Tutorial"
        url: "/test/documentation/index.html"
      - link:
        title: "Download"
        url: "https://..."
    panel:
      - link:
        title: How to start?
        url: "#start"    
      - link:
        title: Add new project 
        url: "#new-project"
      - link:
        title: Write project demo
        url: "#demo"
      - link:
        title: Write tutorial page
        url: "#demo"        
      - link:
        title: Jekyll modifications
        url: "#jekyll"